data_path: "../data/raw/data.xls"
model_path: "models/gradient_boosting.pkl"
transformer_path: "../models/transformer.pkl"
metric_path: "models/metrics.json"
log_path: "../configs/logging_config.yaml"
splitting_params:
  val_size: 0.2
  random_state: 10
  stratify: True
model_type: "GradientBoostingClassifier"
feature_params:
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "fbs"
    - "thalach"
    - "oldpeak"
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  target_col: "target"
gs_params:
  'param_grid':
    'learning_rate':
      - 0.01
      - 0.05
      - 0.1
      - 0.2
    'max_depth':
      - 2
      - 3
      - 4
    'n_estimators':
      - 50
      - 75
      - 100
  'cv': 4
  'scoring': 'roc_auc'
